# Generated by Django 4.1.3 on 2022-12-10 13:05

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='cooling',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
