# Generated by Django 4.1.3 on 2022-12-10 13:22

from django.db import migrations, models

from ..models import Bikes


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bikes_cooling'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='disc',
            field=models.BooleanField(default=False),
        ),
    ]

    

platina = Bikes()

platina.name = 'Platina'
platina.capacity = 100
platina.price = 65000
platina.description = ' Low Budget Bike for Starters'
platina.cooling = 'air cooling'

