# Generated by Django 4.1.3 on 2022-12-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bikes_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='image',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
